"""Registry of analyzed repositories.

`roots` are directories (relative to the checkout) whose .lean files form the
library proper — tests, blueprints, docs and vendored code are excluded.
`deps` list upstream repos whose declaration names should be resolvable, in
priority order (first shadows later).
"""

REPOS = {
    "core": dict(
        label="Lean 4 core (Init+Std+Lean)",
        url="https://github.com/leanprover/lean4",
        dir="lean4",
        roots=["src/Init", "src/Std", "src/Lean"],
        deps=[],
        category="core infrastructure",
        stars=8512,
        provenance="human",
    ),
    "batteries": dict(
        label="Batteries",
        url="https://github.com/leanprover-community/batteries",
        dir="batteries",
        roots=["Batteries"],
        deps=["core"],
        category="core infrastructure",
        stars=407,
        provenance="human",
    ),
    "aesop": dict(
        label="Aesop",
        url="https://github.com/leanprover-community/aesop",
        dir="aesop",
        roots=["Aesop"],
        deps=["batteries", "core"],
        category="core infrastructure",
        stars=383,
        provenance="human",
    ),
    "mathlib4": dict(
        label="Mathlib",
        url="https://github.com/leanprover-community/mathlib4",
        dir="mathlib4",
        roots=["Mathlib"],
        deps=["batteries", "aesop", "core"],
        category="flagship library",
        stars=3628,
        provenance="human",
    ),
    "cslib": dict(
        label="CSLib",
        url="https://github.com/leanprover/cslib",
        dir="cslib",
        roots=["Cslib"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="curated library",
        stars=627,
        provenance="human",
    ),
    "physlib": dict(
        label="Physlib",
        url="https://github.com/leanprover-community/physlib",
        dir="physlib",
        roots=["Physlib", "QuantumInfo"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="curated library",
        stars=649,
        provenance="human+AI",
    ),
    "scilean": dict(
        label="SciLean",
        url="https://github.com/lecopivo/SciLean",
        dir="scilean",
        roots=["SciLean"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="curated library",
        stars=517,
        provenance="human",
    ),
    "flt": dict(
        label="FLT",
        url="https://github.com/ImperialCollegeLondon/FLT",
        dir="flt",
        roots=["FLT"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=943,
        provenance="human",
    ),
    "pfr": dict(
        label="PFR",
        url="https://github.com/teorth/pfr",
        dir="pfr",
        roots=["PFR"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=220,
        provenance="human",
    ),
    "analysis": dict(
        label="Tao Analysis I",
        url="https://github.com/teorth/analysis",
        dir="analysis",
        roots=["Analysis"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=1821,
        provenance="human",
    ),
    "equational_theories": dict(
        label="Equational Theories",
        url="https://github.com/teorth/equational_theories",
        dir="equational_theories",
        roots=["equational_theories"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=540,
        provenance="human+AI",
    ),
    "formal-conjectures": dict(
        label="Formal Conjectures",
        url="https://github.com/google-deepmind/formal-conjectures",
        dir="formal-conjectures",
        roots=["FormalConjectures", "FormalConjecturesForMathlib", "FormalConjecturesUtil"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="statements only",
        stars=1052,
        provenance="human",
    ),
    "nng4": dict(
        label="Natural Number Game",
        url="https://github.com/leanprover-community/NNG4",
        dir="nng4",
        roots=["Game"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="teaching",
        stars=348,
        provenance="human",
    ),
    "tauceti": dict(
        label="TauCeti",
        url="https://github.com/TauCetiProject/TauCeti",
        dir="tauceti",
        roots=["TauCeti"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI-generated library",
        stars=17,
        provenance="AI",
    ),
    "lean-pool": dict(
        label="LeanPool",
        url="https://github.com/Vilin97/lean-pool",
        dir="lean-pool",
        roots=["LeanPool"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI-generated library",
        stars=68,
        provenance="AI",
    ),
    "atlas": dict(
        label="Meta ATLAS",
        url="https://github.com/facebookresearch/atlas-lean",
        dir="atlas-lean",
        roots=["Atlas"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI-generated library",
        stars=273,
        provenance="AI",
    ),
    "seed-prover": dict(
        label="Seed-Prover",
        url="https://github.com/ByteDance-Seed/Seed-Prover",
        dir="seed-prover",
        roots=["SeedProver", "SeedProver-1.5"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI proof dump",
        stars=435,
        provenance="AI",
    ),
    "superhuman": dict(
        label="DeepMind superhuman",
        url="https://github.com/google-deepmind/superhuman",
        dir="superhuman",
        roots=["leap"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI proof dump",
        stars=774,
        provenance="AI",
    ),
    "erdos90": dict(
        label="Erdos90 (OpenAI)",
        url="https://github.com/plby/Erdos90",
        dir="erdos90",
        roots=["src/submission"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI proof project",
        stars=15,
        provenance="AI",
    ),
    "addcombi": dict(
        label="AddCombi",
        url="https://github.com/leanprover-community/add-combi",
        dir="addcombi",
        roots=["AddCombi"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=30,
        provenance="human",
    ),
    "pnt": dict(
        label="PrimeNumberTheorem+",
        url="https://github.com/AlexKontorovich/PrimeNumberTheoremAnd",
        dir="pnt",
        roots=["PrimeNumberTheoremAnd"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=323,
        provenance="human",
    ),
    "carleson": dict(
        label="Carleson",
        url="https://github.com/fpvandoorn/carleson",
        dir="carleson",
        roots=["Carleson"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="research formalization",
        stars=100,
        provenance="human",
    ),
    "strongpnt": dict(
        label="StrongPNT (Math Inc)",
        url="https://github.com/math-inc/strongpnt",
        dir="strongpnt",
        roots=["StrongPNT"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI formalization",
        stars=319,
        provenance="AI",
    ),
    "clawristotle": dict(
        label="Clawristotle",
        url="https://github.com/Vilin97/Clawristotle",
        dir="clawristotle",
        roots=["landau/Aristotle", "grothendieck-vanishing/Aristotle"],
        deps=["mathlib4", "batteries", "aesop", "core"],
        category="AI proof project",
        stars=26,
        provenance="AI",
    ),
}

# Build order: dependencies before dependents.
BUILD_ORDER = [
    "core", "batteries", "aesop", "mathlib4",
    "cslib", "physlib", "scilean", "flt", "pfr", "analysis",
    "equational_theories", "formal-conjectures", "nng4",
    "tauceti", "lean-pool", "atlas", "seed-prover", "superhuman",
    "erdos90", "clawristotle", "addcombi", "pnt", "carleson", "strongpnt",
]

EXCLUDED_DIR_PARTS = {
    ".lake", "lake-packages", "test", "tests", "Test", "Tests",
    "scripts", "docs", "blueprint", "docbuild", "widget", "web",
}
